### ISSUE TITLE
Bottom of left menu not visible

### ISSUE THREAD

**Issue by ghost** [restic/restic.net#6]
I need to zoom out the page by several levels in Firefox to be able to see the whole menu on the left. In fact when I scroll down the page, the menu on the left doesn't scroll. And by default (with the default zoom level) I don't see the whole menu. I have a 15" laptop screen, 1366x768 resolution.

**Comment by fd0** [comment]
Oh, hm. thanks for the report! I'm not really a web designer, can somebody with a bit more experience chime in on what to do here?

**Comment by rawtaz** [comment]
We'll fix it when/after switching to another site generator. Unless someone wants to poke around with Jekyll :)

**Comment by rawtaz** [comment]
@swilmet Can you check this again? We have the Hugo-based "new" site in place now. Just want to know if it's the same problem. Also, are you sure it's not a "default zoom" setting in your browser that's the culpruit?

**Comment by ghost** [comment]
Still the same problem. With a larger screen the problem can be reproduced by resizing the web browser window.

**Comment by rawtaz** [comment]
@swilmet Can you post a screenshot at imgur.com or similar? I really can't reproduce this more than that on my 1280x800 monitor the only thing I don't see in the left menu is the bottom-most License item. If I then just zoom out one single time the menu is smaller and everything shows.

Can someone else reproduce this?

**Comment by rawtaz** [comment]
Closing this due to lack of feedback. Everyone, please feel free to re-open this if you can reproduce this problem - we'd love to know about it if that's the case, so we can fix it!
