### ISSUE TITLE
Migrate from Jekyll to Hugo

### ISSUE THREAD

**Issue by rawtaz** [restic/restic.net#7]
Replace the current site generator Jekyll with Hugo.

**Comment by rawtaz** [comment]
There's now a new `hugo` branch in which the entire site has been migrated.

The embedded forum comments in blog posts are not working, due to unknown reasons but it's a problem in the Discourse forum software. We'll try to fix it when the new site is running on the real server on the real domain, it might be that it will work then.

Also a URL rewrite needs to be added in the web server since the Atom feed changed from a site-wide to category specific, so `https://restic.net/feed.xml` -> `https://restic.net/blog/index.xml`, and there's no way that I could find to add a redirect inside an Atom feed file :(

**Comment by fd0** [comment]
Done, I've merged the branch :)
