### ISSUE TITLE
The asciinema screencast on the homepage is cutoff

### ISSUE THREAD

**Issue by calroc** [restic/restic.net#8]
The asciinema is cut off:
![screencast-too-small](https://user-images.githubusercontent.com/121701/81006976-40b7f600-8e05-11ea-9ba1-a963bb33f98f.png)

**Comment by calroc** [comment]
Fullscreen is kind of a joke eh?

![fullscreen-mode-not](https://user-images.githubusercontent.com/121701/81007516-39ddb300-8e06-11ea-8e8e-a84117128a2f.png)
 I expected the screen to get larger.  Instead the same-sized video plays letterbox-style over a black background.  To be fair the background does take up the full screen.

**Comment by fd0** [comment]
Huh, interesting. Thanks for the hint! I'm pretty sure that was different a while back, we're just including the recording (as JavaScript) directly from Asciinema. Maybe something on their end has changed...

We're reworking the homepage anyway (time to make a new recording).

**Comment by rawtaz** [comment]
@calroc Thanks for reporting. This is not a general problem - when I view the site I see a larger number of columns of text and lines. Not sure why you don't, though. Perhaps it has to do with your browser's font size settings/zoom?

**Comment by calroc** [comment]
@rawtaz I figured that might be the case. I tried a few things before I filed the bug: turning off tracking protection and such.  It's likely Asciinema or just my wonky browser settings.  Sorry for the noise.

**Comment by rawtaz** [comment]
Thanks @calroc for noticing it anyway, in case it would have been something wrong with the site it'd be great to know!
